name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year: [2024]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Make gradlew executable
      working-directory: ./${{ matrix.year }}
      run: chmod +x gradlew
    
    - name: Run tests for ${{ matrix.year }}
      working-directory: ./${{ matrix.year }}
      run: ./gradlew test
