name: Run Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Make gradlew executable
        working-directory: ./Advent-of-Code
        run: chmod +x gradlew
      
      - name: Run tests
        working-directory: ./Advent-of-Code
        run: ./gradlew test